#!/usr/bin/env python3
"""
Generate gallery data from images/gallery/ directory structure.

Usage:
    python scripts/generate-gallery.py

Scans each subdirectory under images/gallery/, discovers image files,
and writes data/gallery-data.js with the galleryData array.
"""

import json
import os
import re
from pathlib import Path

GALLERY_DIR = Path('images/gallery')
OUTPUT_FILE = Path('data/gallery-data.js')

IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif', '.bmp'}


def slug_to_title(name):
    """Convert a hyphenated directory/filename to a clean Title Case."""
    name = name.replace('-', ' ').replace('_', ' ')
    name = re.sub(r'\s+', ' ', name).strip()
    return name.title()


def find_images(directory):
    """Return sorted list of (stem, full_path) for non-WebP images in directory."""
    images = []
    for f in sorted(directory.iterdir()):
        if f.suffix.lower() not in IMAGE_EXTENSIONS:
            continue
        if f.suffix.lower() == '.webp':
            continue
        caption = slug_to_title(f.stem)
        src = str(f).replace('\\', '/')
        images.append({'src': src, 'caption': caption})
    return images


def build_gallery_data():
    """Scan images/gallery/ and build the galleryData structure."""
    gallery = []
    for album_dir in sorted(GALLERY_DIR.iterdir()):
        if not album_dir.is_dir():
            continue
        images = find_images(album_dir)
        if not images:
            print(f"  ⚠  Skipping '{album_dir.name}' — no images found")
            continue
        title = slug_to_title(album_dir.name)
        cover = images[0]['src']
        gallery.append({
            'title': title,
            'cover': cover,
            'images': images,
        })
        print(f"  ✓  {title}: {len(images)} image{'s' if len(images) > 1 else ''}")
    return gallery


def main():
    print("🔍 Scanning images/gallery/ for albums and images...\n")

    if not GALLERY_DIR.exists():
        print(f"  ✗  Directory '{GALLERY_DIR}' not found. Nothing to do.")
        return

    gallery = build_gallery_data()
    if not gallery:
        print("\n  No albums with images found. A minimal stub will be written.")
        gallery = []

    js = '// Auto-generated by scripts/generate-gallery.py — do not edit manually\n'
    js += '// Run `python scripts/generate-gallery.py` to regenerate.\n'
    js += f'const galleryData = {json.dumps(gallery, indent=2)};\n'

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(js)

    print(f"\n✅ Wrote {len(gallery)} album(s) to {OUTPUT_FILE}")
    print("   Include it in index.html before js/script.js:")
    print('   <script src="data/gallery-data.js"></script>')


if __name__ == '__main__':
    main()
